spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/proving_ground # mariadb
    username: root
    password: Likepotato13^^
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create # 애플리케이션 시작할 때마다 스키마 새로 생성
    show-sql: true #추가함.
    properties:
      hibernate:
        format_sql: true
  mvc: # post를 delete로 변경하기 위함
    hiddenmethod:
      filter:
        enabled: true
    #database-platform: org.hibernate.spatial.dialect.mariadb.MariaDB103SpatialDialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: DEBUG