spring:
  datasource:
    #driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:h2:tcp://localhost/~/proving_ground
    username: juykim
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace